site_name: Django RESTQL

theme:
  name: "material"
  language: en
  features:
    - content.code.copy
  palette:
    primary: teal
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/icon.svg
  favicon: img/favicon.svg
extra_css: [extra.css]
repo_name: yezyilomo/django-restql
repo_url: https://github.com/yezyilomo/django-restql/

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true


nav:
  - Intro: index.md
  - Querying Data: querying_data.md
  - Mutating Data: mutating_data.md
  - Settings: settings.md
  - License: license.md