name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.5'
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Upgrade packaging tools
      run: python -m pip install --upgrade pip setuptools virtualenv wheel

    - name: Install dependencies
      run: python -m pip install --upgrade tox tox-py

    - name: Run tox targets for ${{ matrix.python-version }}
      run: tox --py current
